//
//  TranslatePresenter.swift
//  VIPERSBCoreData
//
//  Created Кирилл Лукьянов on 17.11.2019.
//  Copyright © 2019 Кирилл Лукьянов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TranslatePresenter: TranslatePresenterProtocol {

    weak private var view: TranslateViewProtocol?
    var interactor: TranslateInteractorProtocol?
    private let router: TranslateWireframeProtocol

    init(interface: TranslateViewProtocol,
         interactor: TranslateInteractorProtocol?,
         router: TranslateWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func trasnalteWrod(word: String) {
        let yandexEndpoint = YandexLanguageEndpoint.yandex(parameter: ["text": "hello"])
        interactor?.getTranslateData(endpoint: yandexEndpoint)
    }

    func changeLanguageModule() {
        router.showLanguageModule()
    }

}
